apiVersion: v2
name: three-tier-app
description: A Helm chart for 3-tier FastAPI + NGINX + Postgres app
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 15.5.14
    repository: https://charts.bitnami.com/bitnami
