namespace: app

backend:
  image: "your-dockerhub-username/backend:latest"
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    cpuTarget: 50

frontend:
  image: "your-dockerhub-username/frontend:latest"
  replicas: 1
  nodePort: 30080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

postgresql:
  auth:
    username: admin
    password: admin
    database: tasksdb
  primary:
    persistence:
      enabled: false
