global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@example.com'
  smtp_auth_username: 'alerts@example.com'
  smtp_auth_password: 'REPLACE_ME'
  smtp_require_tls: true

route:
  receiver: email-alerts
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: email-alerts
    email_configs:
      - to: 'devops-team@example.com'
